version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: streamflix
      POSTGRES_USER: streamflix_user
      POSTGRES_PASSWORD: secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schemas:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis_password

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://streamflix_user:secure_password@postgres:5432/streamflix
      REDIS_URL: redis://:redis_password@redis:6379
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./security/certificates:/etc/nginx/certs
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
